// Generated by  : ImageConverter 565 v2.2
// Generated from: platform3_1.png
// Time generated: 17/12/2020 17:29:31
// Dimensions    : 10x2 pixels
// Size          : 40 Bytes

#include <pgmspace.h>
#ifndef PROGMEM
#define PROGMEM
#endif

const unsigned short icon_platform3_1[0x14] PROGMEM ={
0xFDE0, 0xFDE0, 0xFDE0, 0xFDE0, 0xFDE0, 0xFDE0, 0xFDE0, 0xFDE0, 0xFDE0, 0xFDE0, 0xFDE0, 0x9CD3, 0x9CD3, 0x9CD3, 0x9CD3, 0x9CD3,   // 0x0010 (16)
0x9CD3, 0x9CD3, 0x9CD3, 0xFDE0, };
